### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by syrinxx** [Leystryku/Nikyuria#2]
Hey Leystruku, i tried to run the premake5.lua says error "solution" so. Im pretty sure i have to compile the files into a DLL? But i cant find anything on YOuTube or google.
BTW Im german ;) i know you are too but if people have this issue to then they can read this

**Comment by thepapanoob** [comment]
faked erstmal syrinxx und meckert rum das der compile fehlschlägt... pfft der code ist outdated und es benötigt Programmierkenntnisse diesen wieder ans laufen zu kriegen!

**Comment by Leystryku** [comment]
well actually, the code for e.g. gmod seems to work out of the box according to people who managed to compile it
