### ISSUE TITLE
Also cant get it to work.

### ISSUE THREAD

**Issue by reaperill** [Leystryku/Nikyuria#3]
tried a few things like running the hooks.cpp using lua_run and tried to open the lua script in game and got the error solution aswell. so could you help out or write a small text tut on how to use it. thanks

**Comment by thepapanoob** [comment]
could you please learn how to shut the fuck up? thanks! dont complain that its not working if you dont know how to programm

**Comment by reaperill** [comment]
hey, dont do that shit to me, it wont decompile in to it properly 
so thats how but fuck u

**Comment by Leystryku** [comment]
I'm sorry, but I'm not helping with the compilation, due to it being relatively easy.
