### ISSUE TITLE
Csgo, Gmod. Issue

### ISSUE THREAD

**Issue by jdog8460** [Leystryku/Nikyuria#6]
So I am having a issue in the injection process I have the folder in my c folder / harddrive And so when I inject I just get a "No Encode codec silk!" or http://prntscr.com/a95hj9 for gmod or csgo. Any way to fix this, It's compiled and everything

**Comment by Leystryku** [comment]
you obviously don't have the folders where they should be, otherwise this wouldnt show up. read the code if you don't believe me.
