### ISSUE TITLE
c: Respond to closed issue.

### ISSUE THREAD

**Issue by jdog8460** [Leystryku/Nikyuria#7]
So like you were saying leystryku i dont have them in the right place but why do you have to have them in the c: folder that seems a bit suspicious it being in the whole part of windows why not documents, or desktop?

**Comment by Leystryku** [comment]
Because desktop/documents are userprofile relative dirs. C:/ is universal. C:/ isn't a "Windows" dir though, C:/Windows is

**Comment by jdog8460** [comment]
Okay, but stull why do you have to have them in your c drive, what does it have to access like why did you code it so it wont work unless its in the c drive

**Comment by Leystryku** [comment]
If I wanted it to work outside of the C drive I'd have to make it automatically grab paths - aka it's more effort.
